--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-07-28 18:08:47

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16433)
-- Name: quiz; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz (
    id integer NOT NULL,
    title character varying(255)
);


ALTER TABLE public.quiz OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16432)
-- Name: quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16438)
-- Name: quiz_question_ids; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_question_ids (
    quiz_id integer NOT NULL,
    question_ids integer
);


ALTER TABLE public.quiz_question_ids OWNER TO postgres;

--
-- TOC entry 4839 (class 0 OID 16433)
-- Dependencies: 216
-- Data for Name: quiz; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz (id, title) FROM stdin;
1	Springles Quiz 1
2	Testing Quiz 1
\.


--
-- TOC entry 4840 (class 0 OID 16438)
-- Dependencies: 217
-- Data for Name: quiz_question_ids; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_question_ids (quiz_id, question_ids) FROM stdin;
1	6
1	14
1	2
1	15
1	4
2	1
2	6
2	3
2	4
\.


--
-- TOC entry 4846 (class 0 OID 0)
-- Dependencies: 215
-- Name: quiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_id_seq', 2, true);


--
-- TOC entry 4693 (class 2606 OID 16437)
-- Name: quiz quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz
    ADD CONSTRAINT quiz_pkey PRIMARY KEY (id);


--
-- TOC entry 4694 (class 2606 OID 16441)
-- Name: quiz_question_ids fks0d7k0yq779g15wmctr0tlnbi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_question_ids
    ADD CONSTRAINT fks0d7k0yq779g15wmctr0tlnbi FOREIGN KEY (quiz_id) REFERENCES public.quiz(id);


-- Completed on 2024-07-28 18:08:48

--
-- PostgreSQL database dump complete
--

